### ISSUE TITLE
License

### ISSUE THREAD

**Issue by timsayshey** [atashbahar/ecardcanvas#1]
This looks like a great project but I couldn't find a license, ie MIT, BSD, Apache, etc.

Could you please add some sort of license file to this project so others can use it and contribute?

Thanks!

**Comment by timsayshey** [comment]
Here are the instructions:

1. Go to your repository
2. Add a new file by clicking the "Create new file" button
3. Type the file name as License.md or License so license picker will show up..then you can choose the type of license

Hope that helps!

**Comment by atashbahar** [comment]
@timsayshey added the license file. Thanks for the recommendation.
