### ISSUE TITLE
Bug: GET /content/Misc/speed_test.jpg 404 (Not Found)

### ISSUE THREAD

**Issue by timsayshey** [atashbahar/ecardcanvas#2]
Getting this error on my Linux server. After further investigation it looks like it's because "Misc" in the editor.js file is capitalized which doesn't match the folder name "misc" which is lowercase. 

I'll submit a pull-request with a fix shortly.

**Comment by atashbahar** [comment]
@timsayshey merged your pull request. Thanks for your contribution.
