### ISSUE TITLE
Editing text, a single change in several blocks

### ISSUE THREAD

**Issue by alexandrly** [atashbahar/ecardcanvas#4]
When you create and re-edit multiple text blocks, editing occurs immediately in several. I downloaded the distribution on [http://web-present.ru/edit2/editor.html](http://web-present.ru/edit2/editor.html) and made a record (in the attachment). On your site this problem is not observed [http://ecardcanvas.com](http://ecardcanvas.com) 

[Video_2018-10-25_111340.zip](https://github.com/atashbahar/ecardcanvas/files/2514141/Video_2018-10-25_111340.zip)

Thank you for amazing ecard editor!

**Comment by timsayshey** [comment]
Interesting @alexandrly - Would you mind submitting a pull request with a fix?

**Comment by alexandrly** [comment]
Hello @timsayshey , i don't work with git, i'm write my solution: scripts/model/text.js 50 line I'm add - if (this.selected)) :

setText: function (txt) {
        if (this.selected) {
        this.title = txt;
        this.txt.setText(txt);}
        if (this.stroke) { this.stroke.setText(txt); }
        this._updateHeight();
        this.redraw();

And it will be grate if somebody fix the issue in console:
The key "target-densitydpi" is not supported.
jquery-1.10.2.js:6569
 The specified value "!" does not conform to the required format.  The format is "#rrggbb" where rr, gg, bb are two-digit hexadecimal numbers.

**Comment by timsayshey** [comment]
Thanks @alexandrly. I submitted a pull request with your fix but it will need to be reviewed and approved by @atashbahar .

In regards to the other bug. Please open a new issue for that.

**Comment by alexandrly** [comment]
Ok!

**Comment by atashbahar** [comment]
Thanks @timsayshey and @alexandrly for your contribution. I merged the ticket.
